apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - name: nodejs-container
        image: oziengbe/redis-node-app:latest
        ports:
        - containerPort: 30200
        env:
        - name: PORT
          value: "30200"
        livenessProbe:
          httpGet:
            path: /
            port: 30200
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 30200
          initialDelaySeconds: 15
          periodSeconds: 10
      