apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 30200
      targetPort: 30200
      
  selector:
    app: nodeapp
